application: positiva-building
version: 1
runtime: go
api_version: go1
handlers:

- url: /images/projects/
  static_dir: images/projects

- url: /bower_components/ 
  static_dir: bower_components
  
- url: /app/ 
  static_dir: app
  
- url: /css/
  static_dir: css

- url: /images/
  static_dir: images
  
- url: /.*
  script: _go_app